---
- hosts: tanglu-chroot-buildd
  connection: chroot
  vars:
    stable: bartholomea
    devel: chromodoris
    releases:
        - "{{ stable }}"
        - "{{ devel }}"
    all_releases:
        - "{{ stable }}"
        - "{{ devel }}"
        - staging
    mirror: "http://archive.tanglu.org/tanglu"
    architectures:
        - amd64
        - i386
  remote_user: root
  sudo: yes
  tasks:

    - shell: touch /tmp/{{ item[0] }}_{{ item[1] }}
      with_nested: 
        - releases
        - architectures
      args:
        creates: /tmp/{{ item[0] }}_{{ item[1] }}

